title:
  Applying the Variational Quantum Eigensolver to the FeMo cofactor of nitrogenase
description:
  A project for the QOSF Mentorship Program (Winter 2020).
plugins:
    - jekyll
    - jekyll-seo-tag
